# Generated by Django 4.0.6 on 2022-08-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_user_followers_list_alter_user_following_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_posts', to='network.post'),
        ),
    ]
